### ISSUE TITLE
启动错误，数据库还原

### ISSUE THREAD

**Issue by qq1176914912** [fanslead/ReverseProxy.Store#3]
您好，打扰了，遇到了几个问题，第一个问题：我下载项目之后 没有还原数据库 直接启动ReverseProxy.Dashboard 项目 报一个错误：The SPA default page middleware could not return the default page '/index.html'"，是不是我还原数据库之后 就行了
第二个问题：您说用Code First还原数据库 具体是要怎么操作呢

**Comment by fanslead** [comment]
第一个是单页面启动的问题，最新代码是分开前端和API，前端是单独启动dashboard的项目就行了。
第二个是EF的问题，搜一下EF的CodeFirst命令就知道了

**Comment by qq1176914912** [comment]
> 第一个是单页面启动的问题，最新代码是分开前端和API，前端是单独启动dashboard的项目就行了。 第二个是EF的问题，搜一下EF的CodeFirst命令就知道了

那是要在哪个项目下使用codefirst命令呢

**Comment by qq1176914912** [comment]
> 第一个是单页面启动的问题，最新代码是分开前端和API，前端是单独启动dashboard的项目就行了。 第二个是EF的问题，搜一下EF的CodeFirst命令就知道了
我从网上找到命令 然后在 ReverseProxy.Store.EFCore项目下 执行 出现下方问题  是需要我自己新建codeFirst项目吗
![QB2TGX0XQQ8 Q))AC7M264](https://user-images.githubusercontent.com/79817742/146718993-7e078ba8-724d-41dd-bd3f-ccac506c5802.png)

**Comment by fanslead** [comment]
WebApi设置为启动项目

**Comment by qq1176914912** [comment]
启动项 设置了 数据库连接字符也改为了自己的 codefirst命令还是有问题
![F1(L75XUJU8}T@P7WGJV 3Q](https://user-images.githubusercontent.com/79817742/146720338-ede1ab20-1bcf-4600-afb6-f9e64f263304.png)

**Comment by fanslead** [comment]
可以试试命令行执行dotnet ef命令
![image](https://user-images.githubusercontent.com/22066473/146721776-36e7f478-805a-4a8c-bc63-f9a984b032d6.png)

**Comment by qq1176914912** [comment]
![image](https://user-images.githubusercontent.com/79817742/146722756-6c91da2e-9ad1-4335-8694-fa2b37f8b7f0.png)
内容如下
The Entity Framework tools version '3.0.0' is older than that of the runtime '6.0.1'. Update the tools for the latest features and bug fixes. See https://aka.ms/AAc1fbw for more information.
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
No DbContext was found in assembly 'ReverseProxy.WebApi'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

**Comment by fanslead** [comment]
大哥，错误提示都那么明显啦~自己搜索引擎查一查就知道啦。这些内容和这程序没啥关联，都是基础的EF问题。我不可能每个错误一步步给你列出来

**Comment by qq1176914912** [comment]
> 大哥，错误提示都那么明显啦~自己搜索引擎查一查就知道啦。这些内容和这程序没啥关联，都是基础的EF问题。我不可能每个错误一步步给你列出来

好的 麻烦了

**Comment by qq1176914912** [comment]
那个 成功后的数据库叫啥名 
![image](https://user-images.githubusercontent.com/79817742/146725065-77df155d-a76e-4802-aa7d-5664b804faaa.png)

**Comment by fanslead** [comment]
数据库取决你连接字符串

**Comment by qq1176914912** [comment]
我连接字符是本地的 yarp数据库 执行完 dotnet的命令 yarp库（已刷新）中还是没有表
![image](https://user-images.githubusercontent.com/79817742/146726652-d80161a7-f662-44bb-9917-4e216915f1ea.png)

**Comment by qq1176914912** [comment]
好了好了 找打了 感谢 作者的耐心指导 万分感谢
![image](https://user-images.githubusercontent.com/79817742/146727923-62066c2d-51b2-4a8f-923c-fef44ce0874c.png)

**Comment by qq1176914912** [comment]
emmm还有一个问题 就是第一个那个 The SPA default page middleware could not return the default page的问题 我在网上找了找
百度到的解决方法 很少  请问 您有什么建议吗

**Comment by fanslead** [comment]
npm install一下前端试试

**Comment by qq1176914912** [comment]
是这样子吗 ？ 试了 不管用

![image](https://user-images.githubusercontent.com/79817742/146733177-f290996b-8a7d-4f63-bb2f-5121e0b7bd69.png)

**Comment by fanslead** [comment]
那你可以直接在ClientApp目录下跑npm start启动前端，不依赖asp.net core的host

**Comment by qq1176914912** [comment]
> npm start

好的

**Comment by qq1176914912** [comment]
> 那你可以直接在ClientApp目录下跑npm start启动前端，不依赖asp.net core的host

成功跑起来了 感谢

**Comment by gzpbx** [comment]
谢谢楼主和作者，ef core 特别是 migrations 不熟悉，遇到了同样的问题。
补充一下，我还必须得在ReverseProxy.Store.EFCore 项目文件中添加 下面才可以执行 dotnet ef migrations add init
![image](https://user-images.githubusercontent.com/1314305/151515022-3eda3bfa-ef78-4611-b3b1-e5ef8de17686.png)

Microsoft.EntityFrameworkCore.Design
