### ISSUE TITLE
redis起到什么作用

### ISSUE THREAD

**Issue by qq1176914912** [fanslead/ReverseProxy.Store#4]
大佬 请问 redis在该项目里起了什么作用 记录最新yarp配置？

**Comment by fanslead** [comment]
用于集群同步热更新配置，比如启动多个host，调用其中一个host去更新配置，其他host需要同步收到通知去更新

**Comment by qq1176914912** [comment]
![image](https://user-images.githubusercontent.com/79817742/147458774-e6122c00-5f6a-4c74-a0df-816d102f1078.png)
这里的写法 有点搞不懂 我调试发现 当程序刚启动时 所有方法都会执行，后面的时候就只到订阅的这句代码，redis发布订阅不是一个发 一个收吗 为什么 后面的 Publish发没有执行呢

**Comment by fanslead** [comment]
这是通过事件触发更新的，publish只有主动更新配置的时候会触发。

**Comment by qq1176914912** [comment]
好的 大佬

**Comment by qq1176914912** [comment]
大佬 还有个问题 你说sub.publish只有主动更新是会触发 就是每当我新增修改删除的时候 向频道发送消息一方在哪里

**Comment by fanslead** [comment]
哪个host触发CURD就从哪个host publish，其他host触发sub

**Comment by qq1176914912** [comment]
emm那意思是 当我利用接口向库中添加数据的时候 就会通过事件触发publish 因为是通过事件触发的 所以 我调试的时候看不到

**Comment by fanslead** [comment]
你可以试着这样换行打断点，同时启动几个host
![image](https://user-images.githubusercontent.com/22066473/147520362-f6632d64-9e63-43fa-b0c3-e4cae0ae677f.png)

**Comment by qq1176914912** [comment]
emmm我现在的疑问是 当我启动项目也就是使用浏览器 调用新增接口后 断点没有进入 publish 难道不应该是 只要有对数据库的操作就要publish吗？

**Comment by fanslead** [comment]
会进入publish的，你可以看console输出的内容

**Comment by qq1176914912** [comment]
好的 这就了解了 我以为平时修改不进去呢  感谢大佬
