### ISSUE TITLE
redis订阅长时间失效

### ISSUE THREAD

**Issue by qq1176914912** [fanslead/ReverseProxy.Store#5]
不好意思大佬 我这里现在是把你的这一个订阅发布拆分成了两个项目 一个订阅一个发布 这两个项目中 都用到了你的ReverseProxy.Store.Distributed这个类库 为什么我这两个项目刚开始可以正常发布和订阅 过一阵子之后 我在发布 另一个项目就订阅不到了呢，但是你的项目我发现就不存在这个问题，大佬有了解吗，麻烦了

**Comment by fanslead** [comment]
可能你打开方式错了哈哈哈，是不是一段时间后你的redis客户端被释放了或者连接中断了

**Comment by qq1176914912** [comment]
可能是 我项目的问题 一个项目是写数据库 然后发布 另一个是订阅 然后读数据库 也不知道中间哪里出了问题  我那个单独写的测试订阅和发布的项目都没事 麻烦大佬了 我在看看吧

**Comment by qq1176914912** [comment]
我是 你的项目 然后 我的项目 都开着 还有那个测试项目  一共3个订阅 服务 然后过段时间 我查看这个频道的订阅数 就我的那个项目掉了 哭了哭了

**Comment by fanslead** [comment]
可以排查下做了什么操作导致订阅断开~

**Comment by qq1176914912** [comment]
好的 感谢大佬指导 麻烦了

**Comment by qq1176914912** [comment]
大佬你这个项目支持 换成sqlite数据库吗

**Comment by fanslead** [comment]
EF Core支持的都支持

**Comment by qq1176914912** [comment]
好的好的 了解
