### ISSUE TITLE
关于 限流 有何想法

### ISSUE THREAD

**Issue by ni-xue** [fanslead/ReverseProxy.Store#6]

**Comment by fanslead** [comment]
限流可以自己做扩展进去呐

**Comment by ni-xue** [comment]
而外加， 感觉改动还是比较大的，我想着要不给他们设计包的仓库提一个问题，但是他们那边的回复也是相当慢的

**Comment by fanslead** [comment]
自己做中间件扩展也不需要改动yarp的源码啊。

**Comment by ni-xue** [comment]
要想控制到每个路由模式，单写中间件就没啥意义了，我想让他本身接口就包含这些东西，另外他默认情况下转发也没有将无法转发的服务屏蔽，这些都要加 也没有那么轻松了

**Comment by fanslead** [comment]
可以自己根据需求定制呗，通过配置项过滤条件之类的

**Comment by ni-xue** [comment]
有空再说吧，目前也只能是基本达标 毕竟也只是 1.0 版本期望不能太高
