### ISSUE TITLE
请教WebSocket的配置

### ISSUE THREAD

**Issue by EachShow** [fanslead/ReverseProxy.Store#7]
大神好，请教用Yarp转发WebSocket的配置，我的WebSocket用的是SinglR写的，后端Hub的Pattern是"/socket/ws"
我路由配置是这样写的，Yarp应该是没有将路由转发过去，后台应用服务器没有收到前端发送过来的连接请求。
方便抽空指导一下么？感激！！！

      "BackRoute_Production_Socket": {
        "ClusterId": "BackGateway",
        "Match": {
          "Hosts": [ "gateway.pc.com" ], // 我开发环境做的本地DNS解释域名
          "Path": "/{appid}/socket/{**remainder}"
        },
        "Transforms": [
          { "PathPattern": "/v1.0/invoke/{appid}/method/socket/{**remainder}" },  // 应用服务和网关都是用Dapr拉起来的
          {
            "RequestHeader": "Upgrade",
            "Set": "WebSocket"
          },
          {
            "RequestHeader": "Connection",
            "Set": "Upgrade"
          },
          {
            "RequestHeaderOriginalHost": "true"
          },
          { "RequestHeadersCopy": "true" }
        ]
      }

**Comment by fanslead** [comment]
参考我写这篇博客看看https://www.cnblogs.com/fanshaoO/p/15561726.html

**Comment by EachShow** [comment]
拜读过了。
我知道问题所在了。我的问题，其实不是yarp的，而是Dapr的问题。
我的应用是Dapr拉起来的，Dapr是处理不了WebSocket的，只能处理Http，和GRPC
谢谢！
