### ISSUE TITLE
yarp一些配置问题

### ISSUE THREAD

**Issue by qq1176914912** [fanslead/ReverseProxy.Store#8]
大佬 我想问一下 yarp可以实现 向后台服务传递客户端提交的证书或证书指定参数，反向传递证书DN序列、TCP复用，X-FORWORD-FOR源地址透传 这些东西吗

**Comment by qq1176914912** [comment]
我看了官方文档 找到了 说X-FORWORD-FOR是默认开启的 但是 tcp复用和反向传递证书DN序列这些 不知道如何配置

**Comment by fanslead** [comment]
官网有的配置就能配，没有的就没得配

**Comment by qq1176914912** [comment]
> 官网有配得配，没有的配配

好吧 知道了
