### ISSUE TITLE
Update to yarp v2.0.0

### ISSUE THREAD

**Issue by totpero** [fanslead/ReverseProxy.Store#9]
Hi, 
The new 2.0.0 version is released, can you update ?
https://github.com/microsoft/reverse-proxy/releases/tag/v2.0.0

Thamks
👍

**Comment by fanslead** [comment]
ok, wait a days.

**Comment by fanslead** [comment]
> Hi, The new 2.0.0 version is released, can you update ? https://github.com/microsoft/reverse-proxy/releases/tag/v2.0.0
> 
> Thamks 👍

already update
